// GENERATED by scripts/audio/generate_aircraft_audio.py; tuning is in docs/data/AIRCRAFT_AUDIO_PROFILES.json.
using Airside.Domain;

namespace Airside.Presentation
{
    public static class AircraftAudioProfiles
    {
        public static AircraftAudioProfile For(AircraftType type)
        {
            return (type?.Id ?? "ATR42") switch
            {
                "ATR42" => new("atr42", 1.000f, 0.860f),
                "SF34" => new("sf34", 0.940f, 0.780f),
                "DH8D" => new("dh8d", 1.030f, 1.000f),
                "E190" => new("e190", 1.130f, 0.870f),
                "A223" => new("a223", 0.980f, 0.840f),
                "A320" => new("a320", 1.040f, 1.000f),
                "B738" => new("b738", 1.080f, 1.020f),
                "B38M" => new("b38m", 0.990f, 0.960f),
                "A21N" => new("a21n", 0.950f, 1.030f),
                "A339" => new("a339", 0.860f, 1.120f),
                "A359" => new("a359", 0.800f, 1.170f),
                "B789" => new("b789", 0.880f, 1.100f),
                "B78X" => new("b78x", 0.850f, 1.140f),
                "B412" => new("b412", 1.000f, 0.950f),
                _ => new("atr42", 1f, 0.86f)
            };
        }
    }
}
