using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.Json;
using Airside.Domain;
using Airside.Simulation;
using Airside.Tests;

// Usage: CareerSim <out-dir> [seeds=5] [max-open-hours=180] [ignored] [style|all]
var outDir = args.Length > 0 ? args[0] : "career-balance";
var seeds = args.Length > 1 ? int.Parse(args[1], CultureInfo.InvariantCulture) : 5;
var maxHours = args.Length > 2 ? double.Parse(args[2], CultureInfo.InvariantCulture) : 180;
// One career balance since ADR 0127; the difficulty column is kept for older reports' shape.
var difficulties = new[] { CareerDifficulty.Standard };
var styles = args.Length > 4 && args[4] != "all"
    ? new[] { Enum.Parse<CareerPlayStyle>(args[4], true) }
    : new[] { CareerPlayStyle.Competent, CareerPlayStyle.Casual };
Directory.CreateDirectory(outDir);

var jobs = (from d in difficulties from s in styles from seed in Enumerable.Range(1, seeds) select (d, s, seed)).ToList();
var results = new CareerRunResult[jobs.Count];
var watch = Stopwatch.StartNew();
// Sequential: the simulation keeps lazily-filled static lookups that are not thread-safe.
for (var i = 0; i < jobs.Count; i++)
{
    var (d, s, seed) = jobs[i];
    results[i] = CareerSimulation.Run(d, s, seed, maxHours);
    Console.WriteLine($"{d,-9} {s,-9} seed {seed}: {results[i].FinalTier} at {results[i].OpenHours:0} h, fleet {results[i].FinalFleet}, ${results[i].FinalFunds:N0} ({watch.Elapsed.TotalSeconds:0}s)");
}

var tiers = new[] { OperatingTier.Regional, OperatingTier.Domestic, OperatingTier.International };
// ADR 0120 active-play checkpoints: the tier is reached by the end of these hours.
var targets = new Dictionary<OperatingTier, (double lo, double hi)>
{
    [OperatingTier.Regional] = (0, 8), [OperatingTier.Domestic] = (8, 35), [OperatingTier.International] = (35, 70)
};

string Cell(IEnumerable<double?> values)
{
    var hit = values.Where(v => v.HasValue).Select(v => v!.Value).OrderBy(v => v).ToList();
    var total = values.Count();
    if (hit.Count == 0) return $"never (0/{total})";
    var median = hit[hit.Count / 2];
    var text = $"{median:0.0} h ({hit.First():0}–{hit.Last():0})";
    return hit.Count < total ? $"{text}, {hit.Count}/{total}" : text;
}

var md = new StringBuilder();
md.AppendLine($"# Career balance report");
md.AppendLine();
md.AppendLine($"Generated by `scripts/career-balance.sh` (ADR 0125). {seeds} seeds per row, runs stop at the finale or {maxHours:0} open hours.");
md.AppendLine("Hours are **open hours** — simulated time outside the 23:00–06:00 curfew, the stand-in for active play hours.");
md.AppendLine("Targets are ADR 0120's active-play checkpoints: Regional ≤ 8 h, Domestic 8–35 h, International 35–70 h, established airline 110–150 h.");
md.AppendLine();
md.AppendLine("| Difficulty | Style | Regional | Domestic | International | Established | Min cash | Final fleet | Stuck flags |");
md.AppendLine("|---|---|---|---|---|---|---|---|---|");
foreach (var d in difficulties)
foreach (var s in styles)
{
    var rows = results.Where(r => r.Difficulty == d && r.Style == s).ToList();
    var cells = tiers.Select(t => Cell(rows.Select(r => r.TierAtOpenHours.TryGetValue(t, out var h) ? h : (double?)null)));
    var finale = Cell(rows.Select(r => r.FinaleAtOpenHours));
    var minCash = rows.Min(r => r.MinFunds);
    var fleet = string.Join("/", rows.Select(r => r.FinalFleet));
    md.AppendLine($"| {d} | {s} | {string.Join(" | ", cells)} | {finale} | ${minCash:N0} | {fleet} | {rows.Sum(r => r.Flags.Count)} |");
}

md.AppendLine();
md.AppendLine("## Contracts and challenges (ADR 0127, totals over all seeds)");
md.AppendLine();
md.AppendLine("| Style | Contracts lapsed | Challenges paid | Daily reports |");
md.AppendLine("|---|---|---|---|");
foreach (var s in styles)
{
    var rows = results.Where(r => r.Style == s).ToList();
    md.AppendLine($"| {s} | {rows.Sum(r => r.ExpiredContracts)} | {rows.Sum(r => r.ChallengesPaid)} | {rows.Sum(r => r.DailyReports)} |");
}

md.AppendLine();
md.AppendLine("## Goal completion (median open hours, all seeds)");
md.AppendLine();
var goalIds = results.SelectMany(r => r.GoalDoneAtOpenHours.Keys).Distinct().ToList();
md.AppendLine("| Goal | " + string.Join(" | ", difficulties.SelectMany(d => styles.Select(s => $"{d} {s}"))) + " |");
md.AppendLine("|---|" + string.Concat(Enumerable.Repeat("---|", difficulties.Length * styles.Length)));
foreach (var goal in goalIds.OrderBy(g => results.Where(r => r.GoalDoneAtOpenHours.ContainsKey(g)).Average(r => r.GoalDoneAtOpenHours[g])))
{
    md.Append($"| {goal} |");
    foreach (var d in difficulties)
    foreach (var s in styles)
        md.Append($" {Cell(results.Where(r => r.Difficulty == d && r.Style == s).Select(r => r.GoalDoneAtOpenHours.TryGetValue(goal, out var h) ? h : (double?)null))} |");
    md.AppendLine();
}

md.AppendLine();
md.AppendLine("## Where runs ended short of the finale");
md.AppendLine();
foreach (var group in results.Where(r => !r.FinaleAtOpenHours.HasValue)
             .GroupBy(r => (r.FinalTier, string.Join("; ", r.OpenGoalsAtEnd))).OrderByDescending(g => g.Count()))
    md.AppendLine($"- {group.Count()}× stuck in **{group.Key.FinalTier}** with open goals: {group.Key.Item2}");

md.AppendLine();
md.AppendLine("## Stuck flags");
md.AppendLine();
foreach (var r in results.Where(r => r.Flags.Count > 0))
    md.AppendLine($"- {r.Difficulty} {r.Style} seed {r.Seed}: {string.Join("; ", r.Flags.Take(5))}{(r.Flags.Count > 5 ? $" (+{r.Flags.Count - 5} more)" : "")}");

md.AppendLine();
md.AppendLine("## Most common refusals (all runs)");
md.AppendLine();
foreach (var (reason, count) in results.SelectMany(r => r.Refusals).GroupBy(p => p.Key)
             .Select(g => (g.Key, g.Sum(p => p.Value))).OrderByDescending(p => p.Item2).Take(15))
    md.AppendLine($"- {count}× {reason}");

File.WriteAllText(Path.Combine(outDir, "report.md"), md.ToString());

var csv = new StringBuilder("difficulty,style,seed,open_hours,sim_hours,funds,reliability,fleet,tier,rotations\n");
foreach (var r in results)
foreach (var s in r.Samples)
    csv.AppendLine(string.Join(",", r.Difficulty, r.Style, r.Seed, s.OpenHours.ToString("0.0", CultureInfo.InvariantCulture),
        s.Hours.ToString("0.0", CultureInfo.InvariantCulture), s.Funds, s.Reliability, s.Fleet, s.Tier, s.Rotations));
File.WriteAllText(Path.Combine(outDir, "daily.csv"), csv.ToString());

File.WriteAllText(Path.Combine(outDir, "runs.json"), JsonSerializer.Serialize(results.Select(r => new
{
    difficulty = r.Difficulty.ToString(), style = r.Style.ToString(), r.Seed,
    tiers = r.TierAtOpenHours.ToDictionary(p => p.Key.ToString(), p => Math.Round(p.Value, 1)),
    goals = r.GoalDoneAtOpenHours.ToDictionary(p => p.Key, p => Math.Round(p.Value, 1)),
    finale = r.FinaleAtOpenHours, openHours = Math.Round(r.OpenHours, 1), r.MinFunds, r.FinalFunds, r.MinReliability,
    r.FinalReliability, finalTier = r.FinalTier.ToString(), r.FinalFleet, r.FinalRotations, r.RecoveryContracts,
    r.OpenGoalsAtEnd, r.Flags, r.Refusals, r.ExpiredContracts, r.ChallengesPaid, r.DailyReports
}), new JsonSerializerOptions { WriteIndented = true }));

Console.WriteLine($"Wrote {outDir}/report.md in {watch.Elapsed.TotalSeconds:0}s");
