#!/usr/bin/env python3
"""Audit the 78 surveyed YPAD buildings: where each height and name comes from (ADR 0198).

Reads the committed OSM snapshot and the generated Simulation/AdelaideBuildings.cs, and writes
docs/data/ypad-buildings-audit.md. Each row says whether the height is surveyed (OSM height=),
derived (building:levels x 3.4 m) or a rule-based default, whether the building is named, and
flags footprints worth a manual check. Run: python3 scripts/audit-ypad-buildings.py [--check]
"""
from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OSM = ROOT / "docs/data/osm/ypad-buildings-2026-09-21.json"
CS = ROOT / "game/Airside/Assets/Airside/Simulation/AdelaideBuildings.cs"
OUT = ROOT / "docs/data/ypad-buildings-audit.md"
ROW = re.compile(r'new AdelaideBuilding\("OSM-(\d+)", "([^"]*)", AdelaideBuildingKind\.(\w+), ([\d.]+)f')


def area_m2(geom):
    lat0 = math.radians(sum(p["lat"] for p in geom) / len(geom))
    pts = [(p["lon"] * 111320 * math.cos(lat0), p["lat"] * 110574) for p in geom]
    return abs(sum(x0 * y1 - x1 * y0 for (x0, y0), (x1, y1) in zip(pts, pts[1:] + pts[:1]))) / 2


def height_source(tags):
    if "height" in tags:
        return "surveyed (OSM height)"
    if "building:levels" in tags:
        return "derived (levels)"
    return "default (rule)"


def build():
    osm = {str(e["id"]): e for e in json.load(open(OSM))["elements"]}
    rows = []
    for m in ROW.finditer(CS.read_text()):
        oid, name, kind, height = m.group(1), m.group(2), m.group(3), float(m.group(4))
        e = osm.get(oid)
        tags = e.get("tags", {}) if e else {}
        area = area_m2(e["geometry"]) if e else 0.0
        flags = []
        if name.startswith("Airport support building"):
            flags.append("unnamed")
        if area < 40:
            flags.append("tiny footprint")
        if height_source(tags).startswith("default"):
            flags.append("height unsourced")
        rows.append((oid, name, kind, height, height_source(tags), area, flags))
    return rows


def render(rows):
    unsourced = sum(1 for r in rows if "height unsourced" in r[6])
    unnamed = sum(1 for r in rows if "unnamed" in r[6])
    lines = [
        "# YPAD building audit",
        "",
        "Generated by `scripts/audit-ypad-buildings.py` from `docs/data/osm/ypad-buildings-2026-09-21.json` and "
        "`AdelaideBuildings.cs`. Do not hand-edit; regenerate.",
        "",
        f"- Buildings: **{len(rows)}**; heights from a source: **{len(rows) - unsourced}**; "
        f"rule-based default heights: **{unsourced}**; unnamed: **{unnamed}**.",
        "- Terminal 1 and the RFDS hangar are audited separately (`AdelaideLayout.Terminals`).",
        "- Default heights are estimates, not measurements. Replace them from imagery or AIP data when available.",
        "",
        "| OSM id | Name | Kind | Height m | Height source | Area m² | Flags |",
        "|---|---|---|---|---|---|---|",
    ]
    for oid, name, kind, h, src, area, flags in sorted(rows, key=lambda r: (r[2], r[1], r[0])):
        lines.append(f"| {oid} | {name} | {kind} | {h:g} | {src} | {area:.0f} | {', '.join(flags)} |")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    text = render(build())
    if "--check" in sys.argv:
        sys.exit(0 if OUT.exists() and OUT.read_text() == text else "audit is stale: rerun without --check")
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}")
