#!/usr/bin/env python3
"""Bake the retained ODbL Parafield geometry into local metre coordinates. No network."""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = json.loads((ROOT / 'docs/data/parafield-layout-source-v01.json').read_text())
LAT0, LON0 = -34.95, 138.53
MLAT, MLON = 110574.0, 111320.0 * math.cos(math.radians(LAT0))
def en(lat, lon): return (lon-LON0)*MLON, (lat-LAT0)*MLAT
a, b = en(-34.9585244,138.5172171), en(-34.9406962,138.5431392)
mid = tuple((x+y)/2 for x,y in zip(a,b))
dx,dz = b[0]-a[0],b[1]-a[1]
length=math.hypot(dx,dz); ux,uz=dx/length,dz/length
def world(p):
    e,n=en(*p); e-=mid[0]; n-=mid[1]
    return e*ux+n*uz,-e*uz+n*ux
cx,cz=world(DATA['centre'])
def point(p):
    x,z=world(p)
    return f'new ParafieldPoint({x-cx:.3f}, {z-cz:.3f})'
features=DATA['features']
def array(ps): return 'new[] { '+', '.join(point(p) for p in ps)+' }'
lines=['// Generated by scripts/generate-parafield-layout.py. OSM contributors, ODbL 1.0.',
       'namespace Airside.Simulation','{','    public static partial class ParafieldLayout','    {',
       f'        public const double CentreX = {cx:.3f}, CentreZ = {cz:.3f};',
       '        public static readonly ParafieldRunway[] Runways = new[]','        {']
for f in sorted((f for f in features if f['kind']=='runway'),key=lambda f:f['ref']):
    # Official airport master plan confirms sealed surfaces and only 03L/21R lit.
    lines.append(f'            new ParafieldRunway("{f["ref"]}", {point(f["points"][0])}, {point(f["points"][-1])}, 18),')
lines+=['        };','        public static readonly ParafieldPoint[][] Taxiways = new[]','        {']
for f in features:
    if f['kind']=='taxiway':lines.append('            '+array(f['points'])+',')
lines+=['        };','        public static readonly ParafieldPoint[][] Aprons = new[]','        {']
for f in features:
    if f['kind']=='apron':lines.append('            '+array(f['points'][:-1])+',')
lines+=['        };','        public static readonly ParafieldPoint[][] Buildings = new[]','        {']
for f in features:
    if f['kind'] in ('building','hangar'):lines.append('            '+array(f['points'][:-1])+',')
# U → J → J3 → H6 → H → B → B5; runway crossings covered by the airport's exclusive corridor reservation.
route=[[-34.78883,138.63196],[-34.790656,138.630317],[-34.791133,138.630026],[-34.791636,138.629898],
       [-34.792136,138.629863],[-34.791979,138.631088],[-34.791704,138.634997],[-34.792761,138.635129],
       [-34.793726,138.635244],[-34.793655,138.63587],[-34.792656,138.63654],[-34.793112,138.637581]]
lines+=['        };', '        public static readonly ParafieldPoint[] ApronToRunway = '+array(route)+';',
        '        public static readonly ParafieldPoint[] Parking = '+array([[-34.7885,138.6328],[-34.7879,138.63335],[-34.7873,138.6339],[-34.7867,138.63445]])+';',
        '        public static readonly ParafieldPoint LandingExit = '+point([-34.799205,138.633617])+';',
        '        public static readonly ParafieldPoint[] RunwayToApron = '+array([[-34.799205,138.633617],[-34.798995,138.633165],[-34.798721,138.632573],[-34.795619,138.634602],[-34.793655,138.63587],[-34.793726,138.635244],[-34.792761,138.635129],[-34.791704,138.634997],[-34.791979,138.631088],[-34.792136,138.629863],[-34.791636,138.629898],[-34.791133,138.630026],[-34.790656,138.630317],[-34.78883,138.63196]])+';',
        '        public static readonly ParafieldPoint[] ParkingLane = '+array([[-34.78863,138.63310],[-34.78803,138.63365],[-34.78743,138.63420],[-34.78683,138.63475]])+';',
        '    }','}']
path=ROOT/'game/Airside/Assets/Airside/Simulation/ParafieldLayout.Generated.cs'
path.write_text('\n'.join(lines)+'\n')
print(f'Baked {len(features)} airport features at {cx:.1f}, {cz:.1f}')
