#!/usr/bin/env python3
"""Generate golf bunker discs for Airside overview (ADR 0207).

Reads docs/data/osm/ypad-map-*.json (© OpenStreetMap contributors, ODbL) and writes
game/Airside/Assets/Airside/Simulation/AdelaideGolfBunkers.cs — packed runway-frame
centres and radii for every closed OSM golf=bunker way.

Presentation draws sand-coloured discs on the surroundings mesh; the 50 m land-cover
grid is unchanged (Golf tint from ADR 0206 stays).

Run: python3 scripts/generate-ypad-golf-bunkers.py
     python3 scripts/generate-ypad-golf-bunkers.py --check
"""
from __future__ import annotations

import argparse
import glob
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ypad_osm import ROOT, OSM_DIR, is_closed, load_snapshot, way_points  # noqa: E402

OUTPUT = os.path.join(ROOT, "game/Airside/Assets/Airside/Simulation/AdelaideGolfBunkers.cs")
MIN_RADIUS = 2.0
MAX_RADIUS = 22.0
CORE_HALF_X = 1600.0
CORE_HALF_Z = 550.0


def latest_snapshot():
    files = sorted(glob.glob(os.path.join(OSM_DIR, "ypad-map-*.json")))
    if not files:
        sys.exit("no docs/data/osm/ypad-map-*.json — run scripts/fetch-ypad-osm.py first")
    return files[-1]


def bunker_disc(way):
    pts = way_points(way)
    if len(pts) < 3:
        return None
    # Drop duplicate closing vertex for centroid.
    ring = pts[:-1] if math.hypot(pts[0][0] - pts[-1][0], pts[0][1] - pts[-1][1]) < 0.5 else pts
    if len(ring) < 3:
        return None
    cx = sum(p[0] for p in ring) / len(ring)
    cz = sum(p[1] for p in ring) / len(ring)
    if abs(cx) < CORE_HALF_X and abs(cz) < CORE_HALF_Z:
        return None
    radius = max(math.hypot(p[0] - cx, p[1] - cz) for p in ring)
    if radius < MIN_RADIUS:
        return None
    radius = min(radius, MAX_RADIUS)
    return (cx, cz, radius)


def collect(snapshot):
    data = load_snapshot(os.path.basename(snapshot))
    discs = []
    for e in data["elements"]:
        tags = e.get("tags") or {}
        if e.get("type") != "way" or tags.get("golf") != "bunker":
            continue
        if not e.get("geometry") or not is_closed(e):
            continue
        disc = bunker_disc(e)
        if disc is not None:
            discs.append(disc)
    discs.sort(key=lambda d: (round(d[0], 3), round(d[1], 3), round(d[2], 3)))
    return discs, data


def render(discs, snapshot_name, osm_base):
    lines = []
    for i, (x, z, r) in enumerate(discs):
        comma = "," if i < len(discs) - 1 else ""
        lines.append(f"            {x:.3f}f, {z:.3f}f, {r:.3f}f{comma}")
    packed = "\n".join(lines)
    return f"""// <auto-generated>
// Generated by scripts/generate-ypad-golf-bunkers.py from docs/data/osm/{snapshot_name}
// (OSM base {osm_base}). Do not edit by hand — change the script and re-run it.
// Map data © OpenStreetMap contributors, available under the ODbL.
// </auto-generated>
namespace Airside.Simulation
{{
    /// <summary>
    /// OSM golf bunker discs in the runway frame (metres): centre x/z and radius,
    /// clamped to [{MIN_RADIUS:g}, {MAX_RADIUS:g}] m. Presentation draws sand discs
    /// on the surroundings mesh (ADR 0207). Fail-soft: an empty list draws nothing.
    /// </summary>
    public static class AdelaideGolfBunkers
    {{
        public const string Attribution = "Golf bunkers © OpenStreetMap contributors (ODbL)";
        public const string SourceSnapshot = "{snapshot_name}";
        public const int Count = {len(discs)};

        /// <summary>Packed triples: centreX, centreZ, radiusMetres.</summary>
        private static readonly float[] Packed =
        {{
{packed}
        }};

        public static int DiscCount => Count;

        public static void Get(int index, out float centreX, out float centreZ, out float radiusMetres)
        {{
            var i = index * 3;
            centreX = Packed[i];
            centreZ = Packed[i + 1];
            radiusMetres = Packed[i + 2];
        }}
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if OUTPUT is stale")
    args = parser.parse_args()

    snapshot = latest_snapshot()
    discs, data = collect(snapshot)
    osm_base = (data.get("osm3s") or {}).get("timestamp_osm_base", "unknown")
    text = render(discs, os.path.basename(snapshot), osm_base)

    if args.check:
        if not os.path.isfile(OUTPUT):
            print(f"ERROR: missing {OUTPUT}", file=sys.stderr)
            return 1
        with open(OUTPUT, encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print(f"ERROR: {os.path.relpath(OUTPUT, ROOT)} is stale — re-run without --check",
                  file=sys.stderr)
            return 1
        print(f"ok: {len(discs)} bunkers match {os.path.relpath(OUTPUT, ROOT)}")
        return 0

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"golf bunkers: {len(discs)} discs from {os.path.basename(snapshot)}")
    print("wrote", os.path.relpath(OUTPUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
