#!/usr/bin/env python3
"""Generate the Gulf St Vincent coastline around Adelaide Airport (YPAD) for Airside.

Reads the committed OpenStreetMap snapshot docs/data/osm/ypad-coastline-2026-09-14.json
(natural=coastline ways, © OpenStreetMap contributors, ODbL) and writes
game/Airside/Assets/Airside/Simulation/AdelaideCoast.cs.

Uses exactly the runway frame of scripts/generate-ypad-layout.py (x along 05->23 from
the threshold midpoint, z to the left / terminal side, metres), imported from it so the
two can never drift apart.

Output:
  Coastline   the mainland coast from Outer Harbor to Hallett Cove, land on the left
              (OSM convention), simplified to SIMPLIFY_METRES.
  SeaPolygon  that coastline extended north and south past the view and closed far out
              in the gulf, for inside/outside tests.

Run: python3 scripts/generate-ypad-coast.py
"""
import importlib.util
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "docs/data/osm/ypad-coastline-2026-09-14.json")
OUTPUT = os.path.join(ROOT, "game/Airside/Assets/Airside/Simulation/AdelaideCoast.cs")

spec = importlib.util.spec_from_file_location("ypad_layout", os.path.join(ROOT, "scripts/generate-ypad-layout.py"))
layout = importlib.util.module_from_spec(spec)
spec.loader.exec_module(layout)

SIMPLIFY_METRES = 6.0
# Straight extensions past the ends of the mapped coast, and how far into the gulf the
# sea polygon closes. Both lie well beyond the 10 km camera far clip.
NORTH_LAT, SOUTH_LAT, GULF_LON = -34.70, -35.20, 138.15


def chain(ways):
    """Join ways end to start by shared node ids; return the longest chain as lat/lon points."""
    by_start = {w["nodes"][0]: w for w in ways}
    ends = {w["nodes"][-1] for w in ways}
    best = []
    for w in ways:
        if w["nodes"][0] in ends:
            continue  # not a chain head
        pts, cur, seen = [], w, set()
        while cur is not None and cur["id"] not in seen:
            seen.add(cur["id"])
            geom = cur["geometry"]
            pts.extend(geom if not pts else geom[1:])
            cur = by_start.get(cur["nodes"][-1])
        if len(pts) > len(best):
            best = pts
    return best


def simplify(pts, tol):
    if len(pts) < 3:
        return pts
    ax, az = pts[0]
    bx, bz = pts[-1]
    dx, dz = bx - ax, bz - az
    length = math.hypot(dx, dz) or 1e-9
    worst, index = -1.0, 0
    for i in range(1, len(pts) - 1):
        px, pz = pts[i]
        d = abs((px - ax) * dz - (pz - az) * dx) / length
        if d > worst:
            worst, index = d, i
    if worst <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[: index + 1], tol)[:-1] + simplify(pts[index:], tol)


def fmt(points):
    lines, row = [], []
    for x, z in points:
        row.append(f"{x:.1f}f, {z:.1f}f")
        if len(row) == 6:
            lines.append("            " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("            " + ", ".join(row) + ",")
    return "\n".join(lines)


def main():
    with open(SOURCE) as f:
        data = json.load(f)
    coast = chain([e for e in data["elements"] if e["type"] == "way"])
    if coast[0]["lat"] < coast[-1]["lat"]:
        raise SystemExit("expected the mainland coast to run north to south (land on the left)")

    local = [layout.local(p) for p in coast]
    simple = simplify(local, SIMPLIFY_METRES)

    north = layout.local({"lat": NORTH_LAT, "lon": coast[0]["lon"]})
    south = layout.local({"lat": SOUTH_LAT, "lon": coast[-1]["lon"]})
    gulf_south = layout.local({"lat": SOUTH_LAT, "lon": GULF_LON})
    gulf_north = layout.local({"lat": NORTH_LAT, "lon": GULF_LON})
    sea = [north] + simple + [south, gulf_south, gulf_north]

    # Sanity: the coast must stay well clear of the airfield ground rectangle (3 900 x 2 800 m).
    nearest = min(math.hypot(x, z) for x, z in simple)
    inside = [p for p in simple if abs(p[0]) < 1950 and abs(p[1]) < 1400]
    if inside:
        raise SystemExit(f"coastline enters the airfield ground rectangle at {inside[0]}")

    base = data["osm3s"]["timestamp_osm_base"]
    out = f"""// <auto-generated>
// Generated by scripts/generate-ypad-coast.py from docs/data/osm/ypad-coastline-2026-09-14.json
// (OSM base {base}). Do not edit by hand — change the script and re-run it.
// Coastline data © OpenStreetMap contributors, available under the ODbL.
// </auto-generated>
namespace Airside.Simulation
{{
    /// <summary>
    /// The Gulf St Vincent coast west of Adelaide Airport in the runway frame (metres):
    /// x along 05→23 from the threshold midpoint, z to the terminal side. Real OSM
    /// coastline, {len(coast)} points simplified to {len(simple)} at {SIMPLIFY_METRES:g} m.
    /// Nearest point {nearest:.0f} m from the runway midpoint.
    /// </summary>
    public static class AdelaideCoast
    {{
        public const string Attribution = "Coastline © OpenStreetMap contributors (ODbL)";

        /// <summary>Nearest coastline point to the runway midpoint, metres.</summary>
        public const float NearestCoastMetres = {nearest:.1f}f;

        /// <summary>Mainland coast north to south, land on the left. x,z pairs.</summary>
        public static readonly float[] Coastline =
        {{
{fmt(simple)}
        }};

        /// <summary>Closed sea outline: the coast extended past the view and closed in the gulf. x,z pairs.</summary>
        public static readonly float[] SeaPolygon =
        {{
{fmt(sea)}
        }};
    }}
}}
"""
    with open(OUTPUT, "w") as f:
        f.write(out)
    print(f"coast: {len(coast)} OSM points -> {len(simple)} simplified; nearest {nearest:.0f} m; wrote {os.path.relpath(OUTPUT, ROOT)}")


if __name__ == "__main__":
    main()
