#!/usr/bin/env python3
"""Generate Adelaide CBD skyline silhouette boxes for Airside (ADR 0208).

Reads the existing DAT-YPAD-SUBURBS snapshot (adelaide-suburb-buildings-*.json,
© OpenStreetMap contributors, ODbL) and writes
game/Airside/Assets/Airside/Simulation/AdelaideCbdSkyline.cs — runway-frame
AABB boxes for sourced-height towers near Victoria Square (~7 km ENE of YPAD).

Presentation draws one grey low-poly mesh; no new licence / no new OSM fetch.

Run: python3 scripts/generate-adelaide-cbd-skyline.py
     python3 scripts/generate-adelaide-cbd-skyline.py --check
"""
from __future__ import annotations

import argparse
import glob
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ypad_osm import ROOT, OSM_DIR, to_local  # noqa: E402

OUTPUT = os.path.join(ROOT, "game/Airside/Assets/Airside/Simulation/AdelaideCbdSkyline.cs")
VS_LAT, VS_LON = -34.9285, 138.5999
MAX_DIST = 2500.0
MIN_HEIGHT = 30.0
MAX_HEIGHT = 200.0
MAX_HALF = 80.0
LEVEL_METRES = 2.9


def latest_snapshot():
    files = sorted(glob.glob(os.path.join(OSM_DIR, "adelaide-suburb-buildings-*.json")))
    if not files:
        sys.exit("no docs/data/osm/adelaide-suburb-buildings-*.json")
    return files[-1]


def number(raw):
    if raw is None:
        return None
    try:
        return float(str(raw).replace("m", "").strip())
    except (TypeError, ValueError):
        return None


def wall_height(tags):
    height = number(tags.get("height"))
    if height is not None:
        return height
    levels = number(tags.get("building:levels"))
    if levels is not None:
        return levels * LEVEL_METRES
    return None


def footprint_box(geometry):
    pts = []
    for p in geometry:
        if isinstance(p, dict):
            pts.append(to_local(float(p["lat"]), float(p["lon"])))
        else:
            lon, lat = float(p[0]), float(p[1])
            pts.append(to_local(lat, lon))
    if len(pts) < 3:
        return None
    xs = [p[0] for p in pts]
    zs = [p[1] for p in pts]
    min_x, max_x = min(xs), max(xs)
    min_z, max_z = min(zs), max(zs)
    cx = 0.5 * (min_x + max_x)
    cz = 0.5 * (min_z + max_z)
    hx = min(MAX_HALF, 0.5 * (max_x - min_x))
    hz = min(MAX_HALF, 0.5 * (max_z - min_z))
    if hx < 1.0 or hz < 1.0:
        return None
    return cx, cz, hx, hz


def collect(snapshot_path):
    with open(snapshot_path, encoding="utf-8") as f:
        data = json.load(f)
    buildings = data["buildings"] if isinstance(data, dict) and "buildings" in data else data.get("elements", [])
    vs = to_local(VS_LAT, VS_LON)
    towers = []
    for b in buildings:
        tags = b.get("tags") or {}
        box = footprint_box(b.get("geometry") or [])
        if box is None:
            continue
        cx, cz, hx, hz = box
        if math.hypot(cx - vs[0], cz - vs[1]) > MAX_DIST:
            continue
        height = wall_height(tags)
        if height is None or height < MIN_HEIGHT or height > MAX_HEIGHT:
            continue
        name = (tags.get("name") or "").replace('"', "'")
        towers.append((int(b["id"]), name, cx, cz, hx, hz, height))
    towers.sort(key=lambda t: t[0])
    return towers, vs


def render(towers, snapshot_name, vs):
    rows = []
    for i, (osm_id, name, cx, cz, hx, hz, height) in enumerate(towers):
        comma = "," if i < len(towers) - 1 else ""
        comment = f" // {name}" if name else ""
        rows.append(
            f"            new CbdSkylineTower({osm_id}L, {cx:.3f}f, {cz:.3f}f, "
            f"{hx:.3f}f, {hz:.3f}f, {height:.3f}f){comma}{comment}"
        )
    body = "\n".join(rows)
    return f"""// <auto-generated>
// Generated by scripts/generate-adelaide-cbd-skyline.py from docs/data/osm/{snapshot_name}
// Do not edit by hand — change the script and re-run it.
// Map data © OpenStreetMap contributors, available under the ODbL.
// </auto-generated>
namespace Airside.Simulation
{{
    /// <summary>One CBD silhouette box in the runway frame (metres), ADR 0208.</summary>
    public readonly struct CbdSkylineTower
    {{
        public CbdSkylineTower(long osmId, float centreX, float centreZ,
            float halfExtentX, float halfExtentZ, float heightMetres)
        {{
            OsmId = osmId;
            CentreX = centreX;
            CentreZ = centreZ;
            HalfExtentX = halfExtentX;
            HalfExtentZ = halfExtentZ;
            HeightMetres = heightMetres;
        }}

        public long OsmId {{ get; }}
        public float CentreX {{ get; }}
        public float CentreZ {{ get; }}
        public float HalfExtentX {{ get; }}
        public float HalfExtentZ {{ get; }}
        public float HeightMetres {{ get; }}
    }}

    /// <summary>
    /// Low-poly Adelaide CBD skyline (~7 km ENE of YPAD): sourced-height OSM
    /// towers near Victoria Square as AABB boxes. Presentation draws one mesh
    /// (ADR 0208). Fail-soft: an empty table draws nothing.
    /// </summary>
    public static class AdelaideCbdSkyline
    {{
        public const string Attribution = "CBD skyline © OpenStreetMap contributors (ODbL)";
        public const string SourceSnapshot = "{snapshot_name}";
        public const int Count = {len(towers)};
        public const float VictoriaSquareX = {vs[0]:.3f}f;
        public const float VictoriaSquareZ = {vs[1]:.3f}f;

        private static readonly CbdSkylineTower[] Towers =
        {{
{body}
        }};

        public static CbdSkylineTower Get(int index) => Towers[index];
    }}
}}
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    snapshot = latest_snapshot()
    towers, vs = collect(snapshot)
    text = render(towers, os.path.basename(snapshot), vs)

    if args.check:
        if not os.path.isfile(OUTPUT):
            print(f"ERROR: missing {OUTPUT}", file=sys.stderr)
            return 1
        with open(OUTPUT, encoding="utf-8") as f:
            current = f.read()
        if current != text:
            print(f"ERROR: {os.path.relpath(OUTPUT, ROOT)} is stale — re-run without --check",
                  file=sys.stderr)
            return 1
        print(f"ok: {len(towers)} towers match {os.path.relpath(OUTPUT, ROOT)}")
        return 0

    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"cbd skyline: {len(towers)} towers from {os.path.basename(snapshot)}")
    print("wrote", os.path.relpath(OUTPUT, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
