#!/usr/bin/env python3
"""Generate the Adelaide Airport (YPAD) aerodrome boundary for Airside.

Reads the committed OpenStreetMap snapshot docs/data/osm/ypad-boundary-2026-09-29.json
(© OpenStreetMap contributors, ODbL; way 146489105, aeroway=aerodrome, icao=YPAD) and writes
game/Airside/Assets/Airside/Simulation/AdelaideBoundary.cs.

Coordinates are the game's runway frame, in metres (see generate-ypad-service-roads.py):
  x — along runway 05/23 from the midpoint of its thresholds, positive towards 23 (NE)
  z — across it, positive to the left of 05→23, i.e. the north-west / terminal side

The outline is simplified (Douglas-Peucker, 2 m) and wound counter-clockwise. Vehicle gates are
placed where the airside-only service roads (docs/data/osm/ypad-service-roads-2026-09-23.json:
access=no) cross the outline, so an opening in the fence sits on a real road.

Run: python3 scripts/generate-ypad-boundary.py
"""
import json
import math
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "docs/data/osm/ypad-boundary-2026-09-29.json")
ROADS = os.path.join(ROOT, "docs/data/osm/ypad-service-roads-2026-09-23.json")
OUTPUT = os.path.join(ROOT, "game/Airside/Assets/Airside/Simulation/AdelaideBoundary.cs")
AERODROME_WAY = 146489105
TOLERANCE = 2.0

LAT0, LON0 = -34.95, 138.53
RWY05 = {"lat": -34.9585244, "lon": 138.5172171}
RWY23 = {"lat": -34.9406962, "lon": 138.5431392}


def xy(p):
    return ((p["lon"] - LON0) * 111320.0 * math.cos(math.radians(LAT0)),
            (p["lat"] - LAT0) * 110574.0)


A, B = xy(RWY05), xy(RWY23)
LENGTH = math.dist(A, B)
U = ((B[0] - A[0]) / LENGTH, (B[1] - A[1]) / LENGTH)
N = (-U[1], U[0])
MID = ((A[0] + B[0]) / 2.0, (A[1] + B[1]) / 2.0)


def local(p):
    q = xy(p)
    v = (q[0] - MID[0], q[1] - MID[1])
    return (v[0] * U[0] + v[1] * U[1], v[0] * N[0] + v[1] * N[1])


def simplify(pts, tol):
    if len(pts) < 3:
        return pts
    (x1, y1), (x2, y2) = pts[0], pts[-1]
    dx, dy = x2 - x1, y2 - y1
    norm = math.hypot(dx, dy) or 1e-9
    best, index = 0.0, 0
    for i in range(1, len(pts) - 1):
        d = abs(dy * pts[i][0] - dx * pts[i][1] + x2 * y1 - y2 * x1) / norm
        if d > best:
            best, index = d, i
    if best <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[:index + 1], tol)[:-1] + simplify(pts[index:], tol)


def area(pts):
    return sum(a[0] * b[1] - b[0] * a[1] for a, b in zip(pts, pts[1:] + pts[:1])) / 2.0


def crossing(p, q, a, b):
    """Point where segment p-q meets segment a-b, else None."""
    r = (q[0] - p[0], q[1] - p[1])
    s = (b[0] - a[0], b[1] - a[1])
    den = r[0] * s[1] - r[1] * s[0]
    if abs(den) < 1e-9:
        return None
    t = ((a[0] - p[0]) * s[1] - (a[1] - p[1]) * s[0]) / den
    u = ((a[0] - p[0]) * r[1] - (a[1] - p[1]) * r[0]) / den
    if 0.0 <= t <= 1.0 and 0.0 <= u <= 1.0:
        return (p[0] + r[0] * t, p[1] + r[1] * t)
    return None


def main():
    doc = json.load(open(SOURCE))
    base = doc.get("osm3s", {}).get("timestamp_osm_base", "unknown")
    way = next(e for e in doc["elements"] if e["id"] == AERODROME_WAY)
    pts = [local(g) for g in way["geometry"]]
    if math.dist(pts[0], pts[-1]) < 0.5:
        pts = pts[:-1]
    if area(pts) < 0:
        pts.reverse()
    # Douglas-Peucker needs an open line: split the ring at its two farthest-apart points.
    far = max(range(len(pts)), key=lambda i: math.dist(pts[0], pts[i]))
    first = simplify(pts[:far + 1], TOLERANCE)
    second = simplify(pts[far:] + [pts[0]], TOLERANCE)
    pts = first[:-1] + second[:-1]

    roads = json.load(open(ROADS))
    nodes = {e["id"]: e for e in roads["elements"] if e["type"] == "node"}
    gates = []
    for w in (e for e in roads["elements"] if e["type"] == "way"):
        if w.get("tags", {}).get("access") != "no":
            continue
        line = [local(nodes[n]) for n in w["nodes"] if n in nodes]
        for p, q in zip(line, line[1:]):
            for a, b in zip(pts, pts[1:] + pts[:1]):
                hit = crossing(p, q, a, b)
                if hit and all(math.dist(hit, g) > 30.0 for g in gates):
                    gates.append(hit)

    perimeter = sum(math.dist(a, b) for a, b in zip(pts, pts[1:] + pts[:1]))
    lines = [
        "// Generated by scripts/generate-ypad-boundary.py. Do not hand-edit.",
        "namespace Airside.Simulation",
        "{",
        "    /// <summary>",
        "    /// The Adelaide Airport (YPAD) aerodrome boundary from OpenStreetMap (ODbL), counter-clockwise,",
        "    /// as x,z pairs in the runway frame, plus the vehicle gates where airside roads leave it.",
        "    /// </summary>",
        "    public static class AdelaideBoundary",
        "    {",
        '        public const string Attribution = "Aerodrome boundary © OpenStreetMap contributors (ODbL)";',
        f'        public const string OsmBase = "{base}";',
        f"        public const float PerimeterMetres = {perimeter:.0f}f;",
        "        public static readonly float[] Outline =",
        "        {",
    ]
    for i in range(0, len(pts), 4):
        lines.append("            " + ", ".join(f"{x:.1f}f, {z:.1f}f" for x, z in pts[i:i + 4]) + ",")
    lines += ["        };", "", "        /// <summary>Vehicle gates as x,z pairs, on the outline.</summary>",
              "        public static readonly float[] Gates ="]
    lines.append("        {")
    for x, z in gates:
        lines.append(f"            {x:.1f}f, {z:.1f}f,")
    lines += ["        };", "    }", "}", ""]
    open(OUTPUT, "w").write("\n".join(lines))
    print(f"{len(pts)} outline points, {perimeter:.0f} m, {len(gates)} gates -> {OUTPUT}")


if __name__ == "__main__":
    main()
