#!/usr/bin/env python3
"""Regenerate scripts/README.md: every script, grouped by what it is for, with its own first descriptive line.

The description comes from the script itself (a module docstring for .py, the first comment line for .sh), so a script that
documents itself in its first lines indexes itself. Nothing here is curated by hand, and the index is never a CI gate.

  python3 scripts/index-scripts.py            rewrite scripts/README.md
  python3 scripts/index-scripts.py --check    fail if it is stale
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIR = ROOT / "scripts"
OUT = DIR / "README.md"

GROUPS = [
    ("generate", "Generate data and art from sources (deterministic; most have `--check`)"),
    ("test", "Checks (shell and Python) that CI or you run"),
    ("review", "Render or capture things for visual review"),
    ("render", "Render previews and sheets"),
    ("audit", "Audits of the repository and assets"),
    ("run", "Longer runs and stage drivers"),
]


def first_line(path: Path) -> str:
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    if path.suffix == ".py":
        try:
            doc = ast.get_docstring(ast.parse(text))
        except SyntaxError:
            doc = None
        if doc:
            for line in doc.splitlines():
                if line.strip():
                    return line.strip()
        for line in text.splitlines():
            if line.startswith("#") and not line.startswith("#!") and line.strip("# ").strip():
                return line.strip("# ").strip()
        return ""
    for line in text.splitlines()[1:40]:
        s = line.strip()
        if s.startswith("#") and not s.startswith("#!") and s.strip("# "):
            return s.strip("# ").strip()
        if s and not s.startswith("#") and not s.startswith("set "):
            break
    return ""


def group_of(name: str) -> str:
    for prefix, _ in GROUPS:
        if name.startswith(prefix + "-") or name.startswith(prefix + "_"):
            return prefix
    return "other"


def build() -> str:
    files = sorted(p for p in DIR.iterdir() if p.is_file() and p.suffix in {".py", ".sh"} and p.name != "README.md")
    dirs = sorted(p for p in DIR.iterdir() if p.is_dir() and not p.name.startswith((".", "__")) and p.name not in {"bin", "obj"})
    buckets: dict[str, list[Path]] = {g: [] for g, _ in GROUPS}
    buckets["other"] = []
    for p in files:
        buckets[group_of(p.name)].append(p)

    out = [
        "# scripts — index",
        "",
        "Generated by `scripts/index-scripts.py` from each script's own first line — **do not hand-edit**; give a new script a one-line",
        "docstring (Python) or comment (shell) and run the generator. It is never a CI gate.",
        f"**{len(files)} scripts in {len([b for b in buckets.values() if b])} groups.** Run Python with `python3 scripts/<name>.py` and shell with `bash scripts/<name>.sh`.",
        "",
        "Start here:",
        "",
        "- `test-unity.sh` — the source of truth: Unity EditMode tests (needs a Mac Unity editor).",
        "- `test-domain.sh` — the headless mirror (`dotnet test`) plus a compile check against Unity's NUnit 3.5; run it before every push.",
        "- `update-harness.py` — regenerate which files the headless harness compiles (CI checks it is current).",
        "- `audit-unity-assets.py`, `sync-art-streaming-assets.sh` — `.meta` GUIDs and the StreamingAssets art mirror.",
        "- `build-mac.sh`, `capture-game.sh` — local Mac build and unattended screenshots.",
        "",
    ]
    labels = dict(GROUPS)
    labels["other"] = "Everything else"
    for group in [g for g, _ in GROUPS] + ["other"]:
        items = buckets[group]
        if not items:
            continue
        out += [f"## {labels[group]}", "", "| Script | What it does |", "|---|---|"]
        for p in items:
            out.append(f"| `{p.name}` | {first_line(p).replace('|', '/') or '*(no description — add a first-line docstring)*'} |")
        out.append("")
    if dirs:
        out += ["## Folders", "", "| Folder | |", "|---|---|"]
        for d in dirs:
            out.append(f"| `{d.name}/` | |")
        out.append("")
    return "\n".join(out)


def main():
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is out of date: run python3 scripts/index-scripts.py")
        print("scripts index is up to date")
        return
    OUT.write_text(text)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
