#!/usr/bin/env python3
"""Regenerate docs/decisions/README.md, the index of decision records (ADRs).

Two filename styles coexist (ADR 2026-10-07-multi-agent-collaboration):
  NNNN-slug.md            the original sequential numbers, 0001..0252 (not renumbered; ten numbers were claimed twice)
  YYYY-MM-DD-slug.md      every ADR from 2026-10-07 on: date + slug, so two tools or accounts can never claim the same number

The index shows only what each ADR says about itself (its title and any `Status:` line). A blank status means "not stated",
not "accepted". Nobody should hand-edit the index: add the ADR file, then run this script (or leave it; it is never a CI gate).

  python3 scripts/index-adrs.py            rewrite the index
  python3 scripts/index-adrs.py --check    fail if the index is stale
"""
from __future__ import annotations

import collections
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DIR = ROOT / "docs/decisions"
OUT = DIR / "README.md"

DATED = re.compile(r"^(\d{4}-\d{2}-\d{2})-(.+)\.md$")
NUMBERED = re.compile(r"^(\d{4})-(?!\d{2}-\d{2}-)(.+)\.md$")


def describe(path: Path) -> tuple[str, str, bool]:
    text = path.read_text(encoding="utf-8", errors="replace")
    heading = re.search(r"^#\s*(.+)$", text, re.M)
    title = (heading.group(1) if heading else path.stem).strip()
    title = re.sub(r"^(ADR\s*)?(\d{4}-\d{2}-\d{2}|0*\d+)\s*[—\-–:.]*\s*", "", title).strip() or path.stem
    status = ""
    m = re.search(r"^(?:[-*]\s*)?\*{0,2}Status:?\*{0,2}:?\s*(.+)$", text, re.M | re.I)
    if m:
        status = re.sub(r"\*+", "", m.group(1)).strip().split(". ")[0][:70]
    superseded = bool(re.search(r"^#+\s*Superseded by", text, re.M | re.I))
    return title[:90], status, superseded


def build() -> str:
    numbered, dated = [], []
    for p in sorted(DIR.glob("*.md")):
        if p.name == "README.md":
            continue
        if DATED.match(p.name):
            dated.append(p)
        elif NUMBERED.match(p.name):
            numbered.append(p)
    by_number = collections.defaultdict(list)
    for p in numbered:
        by_number[p.name[:4]].append(p.name)
    dups = {n: v for n, v in by_number.items() if len(v) > 1}

    out = [
        "# Decision records (ADRs) — index",
        "",
        "Generated by `scripts/index-adrs.py` — **do not hand-edit** (run the script; it is never a CI gate, so a stale index blocks nobody).",
        "Status is only what each ADR states about itself: most do not state one, so a blank means \"not stated\", not \"accepted\" or \"current\".",
        "Nothing here has been judged superseded except where the ADR says so.",
        "",
        "## Rules for new ADRs",
        "",
        "- **Name new ADRs `YYYY-MM-DD-short-slug.md`** (the ADRs numbered 0001–0252 keep their numbers). A date and slug cannot collide the way a",
        "  sequential number did: parallel work claimed " + str(len(dups)) + " numbers twice. Refer to one in code and docs as `ADR 2026-10-08-short-slug`.",
        "- First lines: `# Title`, then `Status: proposed | accepted | superseded by <file>`, then the date, decision, reason, affected systems, migration impact.",
        "- A design change that replaces an earlier ADR adds `Superseded by <file>` to the old one in the same commit.",
        "- Do not add the new ADR to this index by hand; regenerate it.",
        "",
    ]
    if dups:
        out += ["## Duplicated numbers (disambiguate by filename)", ""]
        out += [f"- **{n}**: " + ", ".join(f"`{x}`" for x in v) for n, v in sorted(dups.items())]
        out.append("")
    out += ["## Index", "", "| # / date | Decision | Stated status |", "|---|---|---|"]
    for p in numbered + dated:
        key = p.name[:4] if NUMBERED.match(p.name) else DATED.match(p.name).group(1)
        title, status, sup = describe(p)
        shown = (("Superseded" if sup else "") + (" · " if sup and status else "") + status).replace("|", "/")
        out.append(f"| {key} | [{title.replace('|', '/')}]({p.name}) | {shown} |")
    return "\n".join(out) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT.relative_to(ROOT)} is out of date: run python3 scripts/index-adrs.py")
        print("ADR index is up to date")
        return
    OUT.write_text(text)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
