#!/usr/bin/env python3
"""Keep the headless test harness (scripts/dotnet-harness) in step with the code, automatically.

The harness compiles Domain/Simulation plus whatever Presentation files and EditMode tests do not need
UnityEngine. That list used to be hand-maintained, so a new Unity-free file, or a new test that needed one,
broke or silently left out of the run. This script derives it:

  1. every Presentation .cs file and EditMode test that does not mention UnityEngine/UnityEditor/TMPro;
  2. build the harness; any file that fails to compile (it leans on a Unity-dependent type) is dropped;
  3. repeat until the build is clean.

It writes scripts/dotnet-harness/Harness.Generated.props, which Harness.csproj imports. Run it after adding
a Presentation file or a test; CI runs `--check` and fails if the committed file is stale.

  python3 scripts/update-harness.py            regenerate
  python3 scripts/update-harness.py --check    fail if Harness.Generated.props would change

Needs the .NET 8 SDK on PATH.
"""
import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "game/Airside/Assets/Airside")
HARNESS = os.path.join(ROOT, "scripts/dotnet-harness")
PROPS = os.path.join(HARNESS, "Harness.Generated.props")
UNITY = re.compile(r"\bUnityEngine\b|\bUnityEditor\b|\bTMPro\b|\bUnity\.(Collections|Mathematics|Burst)\b")
# Test files that build but must not run headlessly (they need a real player or are too slow).
NEVER = {"AirsideAircraftRenderBatcherTests.cs", "AircraftPerformanceTests.cs", "AircraftLiveryPaintTests.cs"}


def candidates(sub):
    folder = os.path.join(ASSETS, sub)
    out = []
    for name in sorted(os.listdir(folder)):
        if not name.endswith(".cs"):
            continue
        with open(os.path.join(folder, name), encoding="utf-8") as f:
            code = re.sub(r"/\*.*?\*/|//[^\n]*", "", f.read(), flags=re.S)  # a comment may say "no UnityEngine"
            if not UNITY.search(code):
                out.append(name)
    return out


def write_props(presentation, tests):
    def item(sub, name):
        return f'    <Compile Include="../../game/Airside/Assets/Airside/{sub}/{name}" />'

    lines = ["<!-- GENERATED by scripts/update-harness.py; do not edit by hand. -->", "<Project>", "  <ItemGroup>"]
    lines += [item("Presentation", n) for n in presentation]
    lines += [item("Tests/EditMode", n) for n in tests]
    lines += ["  </ItemGroup>", "</Project>", ""]
    return "\n".join(lines)


def build():
    result = subprocess.run(["dotnet", "build", "--nologo", "-v:q", "-clp:NoSummary"], cwd=HARNESS,
                            capture_output=True, text=True)
    return result.returncode, result.stdout + result.stderr


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    presentation = candidates("Presentation")
    tests = [t for t in candidates("Tests/EditMode") if t not in NEVER]
    original = open(PROPS, encoding="utf-8").read() if os.path.exists(PROPS) else ""
    try:
        run(args, presentation, tests, original)
    except BaseException:
        # never leave a half-derived list behind, whatever went wrong
        with open(PROPS, "w", encoding="utf-8", newline="\n") as f:
            f.write(original)
        raise


def run(args, presentation, tests, original):
    for attempt in range(1, 30):
        with open(PROPS, "w", encoding="utf-8", newline="\n") as f:
            f.write(write_props(presentation, tests))
        code, output = build()
        if code == 0:
            break
        bad = set(re.findall(r"/(Presentation|Tests/EditMode)/([A-Za-z0-9_.]+\.cs)\(\d+,\d+\): error", output))
        if not bad:
            sys.exit("harness build failed for a reason outside Presentation/Tests:\n" + output[-3000:])
        # Prefer dropping Presentation files first: a broken test is usually just a symptom of one.
        drop_p = {n for kind, n in bad if kind == "Presentation"}
        if drop_p:
            presentation = [n for n in presentation if n not in drop_p]
            print(f"attempt {attempt}: dropping {len(drop_p)} Presentation file(s): {', '.join(sorted(drop_p))}")
        else:
            drop_t = {n for kind, n in bad}
            tests = [t for t in tests if t not in drop_t]
            print(f"attempt {attempt}: excluding {len(drop_t)} test(s): {', '.join(sorted(drop_t))}")
    else:
        sys.exit("harness did not converge")
    text = write_props(presentation, tests)
    if args.check:
        with open(PROPS, "w", encoding="utf-8", newline="\n") as f:
            f.write(original)
        if original != text:
            sys.exit("Harness.Generated.props is stale: run python3 scripts/update-harness.py")
        print("Harness.Generated.props is up to date")
        return
    print(f"{len(presentation)} Presentation files and {len(tests)} tests in the headless harness")


if __name__ == "__main__":
    main()
