// <auto-generated>
// Generated by scripts/generate-adelaide-cbd-skyline.py from docs/data/osm/adelaide-suburb-buildings-2026-09-29.json
// Do not edit by hand — change the script and re-run it.
// Map data © OpenStreetMap contributors, available under the ODbL.
// </auto-generated>
namespace Airside.Simulation
{
    /// <summary>One CBD silhouette box in the runway frame (metres), ADR 0208.</summary>
    public readonly struct CbdSkylineTower
    {
        public CbdSkylineTower(long osmId, float centreX, float centreZ,
            float halfExtentX, float halfExtentZ, float heightMetres)
        {
            OsmId = osmId;
            CentreX = centreX;
            CentreZ = centreZ;
            HalfExtentX = halfExtentX;
            HalfExtentZ = halfExtentZ;
            HeightMetres = heightMetres;
        }

        public long OsmId { get; }
        public float CentreX { get; }
        public float CentreZ { get; }
        public float HalfExtentX { get; }
        public float HalfExtentZ { get; }
        public float HeightMetres { get; }
    }

    /// <summary>
    /// Low-poly Adelaide CBD skyline (~7 km ENE of YPAD): sourced-height OSM
    /// towers near Victoria Square as AABB boxes. Presentation draws one mesh
    /// (ADR 0208). Fail-soft: an empty table draws nothing.
    /// </summary>
    public static class AdelaideCbdSkyline
    {
        public const string Attribution = "CBD skyline © OpenStreetMap contributors (ODbL)";
        public const string SourceSnapshot = "adelaide-suburb-buildings-2026-09-29.json";
        public const int Count = 42;
        public const float VictoriaSquareX = 6381.350f;
        public const float VictoriaSquareZ = -2279.924f;

        private static readonly CbdSkylineTower[] Towers =
        {
            new CbdSkylineTower(28812526L, 6615.592f, -1430.377f, 34.579f, 34.891f, 42.000f), // Riverside Centre
            new CbdSkylineTower(41659259L, 6299.059f, -1881.195f, 34.496f, 32.883f, 34.800f), // Australian Taxation Office
            new CbdSkylineTower(52567821L, 6457.754f, -1426.040f, 26.626f, 26.126f, 49.300f), // Oaks Embassy
            new CbdSkylineTower(181219964L, 7367.864f, -842.568f, 14.035f, 35.344f, 51.000f), // St Peter’s Cathedral
            new CbdSkylineTower(186586007L, 6503.129f, -1459.937f, 20.879f, 22.370f, 46.400f), // Oaks Horizons
            new CbdSkylineTower(198702409L, 6680.838f, -1611.670f, 25.170f, 30.683f, 63.800f), // Scape Adelaide Central
            new CbdSkylineTower(219643954L, 6323.694f, -1819.090f, 21.910f, 24.690f, 34.800f),
            new CbdSkylineTower(219643955L, 6380.715f, -1931.978f, 19.760f, 19.417f, 69.000f),
            new CbdSkylineTower(219643956L, 6404.311f, -1889.816f, 18.069f, 20.674f, 31.900f),
            new CbdSkylineTower(220489731L, 6343.683f, -1928.824f, 27.666f, 31.981f, 68.000f), // Telstra
            new CbdSkylineTower(223549549L, 6289.069f, -1799.413f, 32.613f, 27.575f, 40.600f), // Uno Apartments
            new CbdSkylineTower(223549551L, 6242.355f, -1752.827f, 29.873f, 33.453f, 49.300f),
            new CbdSkylineTower(239039010L, 6659.072f, -1578.268f, 20.059f, 19.914f, 40.600f), // Roma Mitchell House
            new CbdSkylineTower(239039030L, 6583.451f, -1620.201f, 25.526f, 32.244f, 34.800f),
            new CbdSkylineTower(243653407L, 6445.287f, -1922.482f, 17.238f, 16.979f, 37.700f),
            new CbdSkylineTower(251079398L, 6482.287f, -1443.796f, 18.045f, 19.369f, 66.700f), // Little National Hotel
            new CbdSkylineTower(251079399L, 6721.938f, -1615.086f, 15.922f, 17.392f, 31.900f),
            new CbdSkylineTower(252074223L, 6379.121f, -2043.728f, 35.628f, 37.010f, 49.300f),
            new CbdSkylineTower(253721089L, 5997.784f, -1737.766f, 20.724f, 22.489f, 52.200f),
            new CbdSkylineTower(256930949L, 6556.864f, -1807.557f, 14.068f, 15.684f, 31.900f),
            new CbdSkylineTower(271422949L, 6997.000f, -1066.627f, 65.368f, 53.132f, 40.000f), // Riverbank Stand
            new CbdSkylineTower(275146796L, 6176.682f, -2069.912f, 17.986f, 17.444f, 49.300f), // The Rowlands
            new CbdSkylineTower(279789796L, 6102.589f, -1794.425f, 25.740f, 25.108f, 52.200f), // Vision on Morphett
            new CbdSkylineTower(284156824L, 6229.111f, -1946.885f, 17.052f, 17.994f, 31.900f), // Quest
            new CbdSkylineTower(285453372L, 6036.400f, -1680.266f, 25.573f, 23.430f, 49.300f), // The Cullinan
            new CbdSkylineTower(285842473L, 5893.785f, -1579.418f, 21.559f, 28.085f, 46.400f), // Scape Waymouth
            new CbdSkylineTower(285843270L, 5897.713f, -1901.775f, 19.420f, 23.243f, 52.200f), // Central Adelaide Apartments
            new CbdSkylineTower(286366034L, 6542.858f, -1568.159f, 21.182f, 17.770f, 40.600f),
            new CbdSkylineTower(287495380L, 5451.579f, -1850.403f, 20.995f, 18.686f, 34.800f),
            new CbdSkylineTower(311499572L, 6007.127f, -2354.718f, 18.752f, 17.891f, 52.200f), // Hotel Indigo
            new CbdSkylineTower(341445947L, 6294.443f, -1998.870f, 28.751f, 26.685f, 55.100f),
            new CbdSkylineTower(404706284L, 5788.790f, -2213.767f, 29.562f, 33.004f, 46.400f), // Bohem
            new CbdSkylineTower(553906582L, 5849.459f, -1419.221f, 30.251f, 34.792f, 49.300f), // 89 - 109 Gray Street
            new CbdSkylineTower(553906589L, 6275.625f, -1201.429f, 39.019f, 42.965f, 70.000f), // Adelaide Health & Medical Sciences
            new CbdSkylineTower(553906592L, 6371.182f, -1267.708f, 36.866f, 36.459f, 40.600f), // Bradley Building
            new CbdSkylineTower(621879217L, 6999.720f, -1069.726f, 66.538f, 39.417f, 40.000f),
            new CbdSkylineTower(925788186L, 6783.014f, -1418.648f, 34.319f, 36.535f, 34.800f), // Eos by SkyCity
            new CbdSkylineTower(971999300L, 6387.646f, -1669.700f, 25.775f, 28.856f, 95.700f), // Sofitel Adelaide
            new CbdSkylineTower(1285172442L, 6805.980f, -1509.240f, 33.723f, 36.172f, 115.000f), // Festival Tower
            new CbdSkylineTower(1298909008L, 6256.233f, -1966.736f, 27.358f, 25.550f, 46.400f), // PWC Building
            new CbdSkylineTower(1376925785L, 6237.107f, -2152.576f, 19.687f, 20.469f, 121.000f), // Victoria Tower
            new CbdSkylineTower(1387269985L, 6201.705f, -1128.692f, 25.028f, 31.898f, 74.000f) // Australian Bragg Centre
        };

        public static CbdSkylineTower Get(int index) => Towers[index];
    }
}
