// <auto-generated>
// Generated by scripts/generate-airport-gates.py from docs/data/osm/airport-gates-2026-10-08.json.
// Source data (c) OpenStreetMap contributors, available under the ODbL. Do not edit by hand.
// </auto-generated>

using System.Collections.Generic;
using Airside.Domain;

namespace Airside.Simulation
{
    /// <summary>Real gate numbers by terminal for the airports OpenStreetMap maps in enough detail.</summary>
    internal static class AirportGateData
    {
        public static bool TryFor(string icao, out TerminalTemplate[] terminals)
        {
            terminals = null;
            switch (icao)
            {
                case "YBAS":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal", GateUse.Domestic, 'C', false, "QFA QLK VOZ JST REX", "2", "3", "4", "5", "6", "7", "8", "9"),
                    };
                    return true;
                case "YBBN":
                    terminals = new[]
                    {
                        Terminal("INT", "International Terminal", GateUse.International, 'E', true, "", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86"),
                        Terminal("DOM", "Domestic Terminal", GateUse.Domestic, 'C', true, "QFA QLK VOZ JST REX", "2", "3", "5", "6", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "38", "39", "40A", "40B", "41", "42", "43", "44A", "44B", "45", "46", "47", "48", "49", "50", "A1", "A4"),
                    };
                    return true;
                case "YBCG":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal", GateUse.Domestic, 'C', true, "QFA QLK VOZ JST REX", "D5", "D6", "D7", "D8/I30", "D9", "D10/I31", "D11/I32", "D12", "D13", "D14", "D15/I34", "D16/I35", "D17", "D18", "D19/I36", "D20/I37", "D21/I38", "D22/I39", "D23/I40"),
                    };
                    return true;
                case "YMML":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal 1 (Qantas)", GateUse.Domestic, 'C', true, "QFA QLK", "1", "2", "3", "4", "6", "7", "8", "9", "10", "11", "12", "21", "22", "23", "24", "25", "26", "27/29", "28/30"),
                        Terminal("T2", "Terminal 2 (International)", GateUse.International, 'E', true, "", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12/14", "16", "18", "20"),
                        Terminal("T3", "Terminal 3 (Virgin Australia)", GateUse.Domestic, 'C', true, "VOZ", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10"),
                        Terminal("T4", "Terminal 4 (Jetstar, Rex)", GateUse.Domestic, 'C', false, "JST REX", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52"),
                    };
                    return true;
                case "YPDN":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal", GateUse.Swing, 'C', true, "QFA QLK VOZ JST REX", "3", "4", "5/6", "7/8", "9", "10"),
                    };
                    return true;
                case "YPPH":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal 1 (gates 10-24)", GateUse.Swing, 'E', true, "VOZ", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "21", "22", "23", "24"),
                        Terminal("Q1", "Qantas gates 143-156", GateUse.Domestic, 'C', true, "QFA QLK", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156"),
                        Terminal("Q2", "Qantas gates 201-219", GateUse.Domestic, 'C', true, "QFA QLK JST", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214"),
                        Terminal("T2", "Regional gates 501-604", GateUse.Domestic, 'B', false, "REX", "501", "502", "503", "504", "505", "506", "507", "508", "509", "510", "511", "512", "601", "602", "603", "604"),
                    };
                    return true;
                case "YSCB":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal", GateUse.Domestic, 'C', true, "QFA QLK VOZ JST REX", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "14A", "15"),
                    };
                    return true;
                case "YSSY":
                    terminals = new[]
                    {
                        Terminal("T1", "Terminal 1 (International)", GateUse.International, 'E', true, "", "8", "9", "10", "24", "25", "26A", "26B", "26C", "26D", "26E", "26F", "26G", "30", "31", "32", "33", "34", "35", "36", "37", "50", "51", "53", "54", "55", "56", "57", "58", "59", "60", "61", "63", "B"),
                        Terminal("T2", "Terminal 2 (Jetstar, Virgin)", GateUse.Domestic, 'C', true, "JST VOZ", "31", "32", "33", "34", "35", "36", "38", "39", "40/40A", "41", "42/44", "43/45", "52", "53", "54", "55", "56", "57", "58", "59", "G1", "G2", "G7"),
                        Terminal("T3", "Terminal 3 (Qantas, Rex)", GateUse.Domestic, 'C', true, "QFA QLK REX", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "16", "17", "19", "49"),
                    };
                    return true;
            }

            return false;
        }

        private static TerminalTemplate Terminal(string id, string name, GateUse use, char code, bool aerobridge,
            string carriers, params string[] gateRefs)
        {
            var gates = new List<GateTemplate>(gateRefs.Length);
            foreach (var gate in gateRefs)
            {
                // A "D10/I31" gate serves both flows; a "D5" or "I3" gate only its own.
                var swing = gate.Contains("/") && gate.StartsWith("D") && gate.Contains("I");
                gates.Add(new GateTemplate(id + "-" + gate, id, code, aerobridge, swing ? GateUse.Swing : use, FactBasis.Inferred));
            }

            return new TerminalTemplate(id, name, gates, carriers.Split(new[] { ' ' }, System.StringSplitOptions.RemoveEmptyEntries));
        }
    }
}
